# Change these first
owner: caballeto # Your GitHub organization or username, where this repository lives
repo: status-page-template # The name of this repository

sites:
  - name: Gawq
    url: https://www.gawq.com
    icon: https://www.gawq.com/assets/img/favicon.png
  - name: Gawq Business API
    url: https://api.gawq.com
    icon: https://www.gawq.com/assets/img/favicon.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status-page-template
  logoUrl: https://www.gawq.com/assets/img/logo-thumb.png
  favicon: https://www.gawq.com/assets/img/favicon.png
  name: Status
  introTitle: "**Gawq** is a news startup building consumer and business solutions."
  introMessage: Gawq gathers hundreds of thousands of news articles daily, performs analysis and offers deep insights into what is happening in the world.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
