# Change these first
owner: caballeto # Your GitHub organization or username, where this repository lives
repo: status-page-template # The name of this repository

sites:
  - name: Gawq
    url: https://www.gawq.com
  - name: Gawq Business API
    url: https://api.gawq.com
  - name: Google
    url: https://www.google.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status-page-template
  logoUrl: https://www.gawq.com/assets/img/logo-thumb.png
  name: Gawq Status
  introTitle: "**Gawq** is a news startup building consumer and business solutions."
  introMessage: Gawq gathers hundreds of thousands of news articles daily, performs analysis and offers deep insights into what is happening in the world. Below is the website and API status of Gawq.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
